---
title: "Mapping US Population by County"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, echo=FALSE}
setwd("C:/Users/yungz/Desktop/Ben R/R Projects/US Counties and Population/US Counties")
load(".RData")
library(flexdashboard)
library(leaflet)
library(tidyverse)
library(DT)
```

```{r echo=FALSE}
pal <- colorBin(
  palette = "Blues", bins = c(86,25000,50000,100000,500000,1000000,5000000,10000000,10039107))
```


Map
=====================================

```{r warning=FALSE, message=FALSE}
leaflet(us_counties_json) %>%
  setView(-93.65, 42.0285, zoom = 4) %>%
  addTiles() %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 1,
              fillColor = ~pal(us_counties_json$merged_us_counties_POPESTIMATE2019)) %>%
  addLegend(position = "bottomleft", pal = pal, 
            values = ~na.omit(us_counties_json$merged_us_counties_POPESTIMATE2019),
            title = "2019 Population Estimates")
```

Table
=====================================

```{r}
DT::datatable(
  table_data,
  filter = "top",
  extensions = "Scroller",
  rownames = FALSE,
  style = "bootstrap",
  class = "compact",
  width = "100%",
  options = list(deferRender = TRUE, scrollY = 300, scroller = TRUE))
```

